services:
    combodo_doctrine_encrypt.orm_subscriber:
        class: Combodo\DoctrineEncryptBundle\Subscribers\DoctrineEncryptSubscriber
        arguments: ["@annotation_reader", "%combodo_doctrine_encrypt.encryptor_class_name%", "%combodo_doctrine_encrypt.secret_key%"]
        tags:
            -  { name: doctrine.event_subscriber }
    combodo_doctrine_encrypt.subscriber:
        alias: combodo_doctrine_encrypt.orm_subscriber
    combodo_doctrine_encrypt.encryptor:
        class: Combodo\DoctrineEncryptBundle\Services\Encryptor
        arguments:
            - "%combodo_doctrine_encrypt.encryptor_class_name%"
            - "%combodo_doctrine_encrypt.secret_key%"
