services:
    combodo_encrypt.twig_extension:
        class: Combodo\DoctrineEncryptBundle\Twig\EncryptExtension
        arguments: ["@combodo_doctrine_encrypt.encryptor"]
        public: false
        tags:
            - { name: twig.extension }
